---
title: "MSHS Census Trends Dashboard"
author: "HSO"
output: 
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true

---
  
#### Report created on `r format(Sys.Date(), "%m/%d/%y")`
#### Census data available through `r format(Sys.Date() - 1, "%m/%d/%y")`
```{r Install and load packages, include = FALSE, echo = FALSE, warning = FALSE, message = FALSE}
# install.packages("dplyr")
# install.packages("lubridate")
# install.packages("readxl")
# install.packages("writexl")
# install.packages("ggplot2")
# install.packages("lubridate")
# install.packages("reshape2")
# install.packages("svDialogs")
# install.packages("stringr")
# install.packages("formattable")
# install.packages("scales")
# install.packages("knitr")
# install.packages("rmarkdown")
# install.packages("kableExtra")

library(dplyr)
library(lubridate)
library(readxl)
library(writexl)
library(ggplot2)
library(lubridate)
library(reshape2)
library(svDialogs)
library(stringr)
library(formattable)
library(scales)
library(knitr)
library(rmarkdown)
library(kableExtra)

```


```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.align = "center")
```


```{r Determine drive mapping}
# if (list.files("J://") == "Presidents") {
#   user_directory <- "J:/Presidents/HSPI-PM/Operations Analytics and Optimization/Projects/System Operations/COVID Scenario Testing"
# } else {
#   user_directory <- "J:/deans/Presidents/HSPI-PM/Operations Analytics and Optimization/Projects/System Operations/COVID Scenario Testing"
# }

```

```{r Import 2019 census data}
ip_census_2019_df <- read_xlsx(path = paste0(user_directory,
                                             "/Epic Census Trending/Epic FY2019 IP Census Summary 2020-08-14.xlsx"),
                               col_types = c("text", "date", "text", "text", 
                                             "numeric", "numeric", "numeric", 
                                             "text", "text", "text", "text", "numeric"), 
                               na = c("", "NA"))

```


```{r Import reference data for unit mappings, admit source, and admit type}
ref_sheet_names <- excel_sheets(path = paste0(user_directory, "/Epic Census Trending/Epic-Oracle-Census-Unit-Mappings-2020-08-05.xlsx"))

ref_data <- lapply(ref_sheet_names, function(x) {read_xlsx(path = paste0(user_directory, "/Epic Census Trending/Epic-Oracle-Census-Unit-Mappings-2020-08-05.xlsx"), sheet = x, na = c("", "NA"))})

unit_mapping <- ref_data[[1]]

admit_source_mapping <- ref_data[[2]]

admission_type_mapping <- ref_data[[3]]

```

```{r Reference data}
# Order unit types for plotting
unit_type_order <- c("ICU", "Med Surg", "COVID Surge", "Peds & Peds ICU", "L&D & Postpartum",
                     "Nursery & NICU", "Psych & Rehab", "ED", "Psych ED", "Non-IP")

# Sinai color schemes
sinai_colors <- c("#221f72", "#00AEEF", "#D80B8C", "#4C4D4C", "#8988dd", "#B2B3B2", "#F887CE", "#79DCFF", "#8F075B", "#00668A")

# Assume 4 week lookback period for now
lookback_period <- 28

# Select maximum number of units per graph
max_num_units <- 8

# Determine start date for trending data based on lookback period
start_date <- (Sys.Date() - 1) - (lookback_period)

# Select the number of months of ADC to compare data from 2019 to 2020
months_to_compare <- 3

# MSB Epic go-live date
msb_epic_start <- as.Date("09/08/2019", format = "%m/%d/%Y")

```


```{r Subset, format, and crosswalk Oracle census and COVID data from 2020}

# # Remove duplicates and select relevant columns from COVID data
# covid_census_subset <- unique(oracle_covid_census_df)
# 
# covid_census_subset <- covid_census_subset %>%
#   select(CSN, MRN, EXTERNAL_ENC_ID, CENSUS_DATE, 
#          CENSUS_DEPT, CENSUS_ROOM, CENSUS_BED,
#          ACCOMMODATION_DESC,
#          PAT_DAY_INF_STATUS) %>%
#   arrange(CSN, CENSUS_DATE, CENSUS_DEPT)

# Remove duplicates from IP census data
ip_census_subset <- unique(oracle_ip_census_df)

ip_census_subset <- ip_census_subset %>%
  arrange(CSN, CENSUS_DATE, CENSUS_DEPT)

# Format census date and year
ip_census_subset <- ip_census_subset %>%
  mutate(CensusDate = as.Date(CENSUS_DATE),
         CensusYear = year(CensusDate),
         CensusMonth = month(CensusDate))
  
# # Crosswalk IP census with COVID data to determine daily COVID volume
# ip_census_crosswalk <- left_join(ip_census_subset, covid_census_subset,
#                                  by = c("CSN" = "CSN", 
#                                         "MRN" = "MRN",
#                                         "EXTERNAL_ENC_ID" = "EXTERNAL_ENC_ID",
#                                         "CENSUS_DATE" = "CENSUS_DATE", 
#                                         "CENSUS_DEPT" = "CENSUS_DEPT",
#                                         "CENSUS_ROOM" = "CENSUS_ROOM",
#                                         "ACCOMMODATION_DESC" = "ACCOMMODATION_DESC",
#                                         "CENSUS_BED" = "CENSUS_BED"))

# # Format crosswalked data patient infection status
# ip_census_crosswalk <- ip_census_crosswalk %>%
#   mutate(AdjPatInfStat = ifelse(PAT_DAY_INF_STATUS %in% c("COVID-19", "PUI - COVID", "SUSC COVID"),
#                        PAT_DAY_INF_STATUS, NA))


# Crosswalk census data with unit mappings
ip_census_crosswalk <- left_join(ip_census_subset, unit_mapping,
                                 by = c("CENSUS_DEPT" = "CENSUS_DEPT"))

# Crosswalk census data with admit source
admit_source_mapping <- admit_source_mapping %>%
  mutate(`EPIC AdmissionSource` = toupper(`EPIC AdmissionSource`))

ip_census_crosswalk <- left_join(ip_census_crosswalk, admit_source_mapping,
                                 by = c("ADMIT_SOURCE" = "EPIC AdmissionSource"))

# Crosswalk census data with admission type
admission_type_mapping <- admission_type_mapping %>%
  mutate(`EPIC AdmissionType` = toupper(`EPIC AdmissionType`))

ip_census_crosswalk <- left_join(ip_census_crosswalk, admission_type_mapping,
                                 by = c("ADMISSION_TYPE" = "EPIC AdmissionType"))

# Manually update Admission Types of Premature as Newborns
ip_census_crosswalk <- ip_census_crosswalk %>%
  mutate(ADMIT_TYPE_DESC_MSX = ifelse(ADMISSION_TYPE == "PREMATURE", 
                                      "NEWBORN - USE OF THIS CODE NECESSITATES THE USE OF SPECIAL CODES IN THE SOURCE OF ADMISSIONá(DATA ELEMENT 13).", 
                                      ADMIT_TYPE_DESC_MSX))



# Order data based on unit type
ip_census_crosswalk$UnitRollUp <- factor(ip_census_crosswalk$UnitRollUp, 
                                         levels = unit_type_order, ordered = TRUE)


```

```{r Crosswalk FY2019 IP census with unit types}

ip_census_2019_df <- left_join(ip_census_2019_df, unit_mapping,
                               by = c("CENSUS_DEPT" = "CENSUS_DEPT"))

ip_census_2019_df <- ip_census_2019_df %>%
  mutate(CensusDate = as.Date(CensusDate),
         CensusMonth = month(CensusDate),
         CensusYear = year(CensusDate))

ip_census_2019_df$UnitRollUp <- factor(ip_census_2019_df$UnitRollUp,
                                       levels = unit_type_order, ordered = TRUE)

# Remove unknown sites and MSB data from before Epic go-live
ip_census_2019_df <- ip_census_2019_df %>%
  filter(IPUnit & !is.na(CensusSite) & !(CensusSite == "MSB" & CensusDate < msb_epic_start))

```


```{r Summarize FY2019 data based on site and unit type}

# Summarize total monthly census for each unit organized by site and unit type/roll up; this will be used to compare 2019 to 2020 ADC
monthly_census_fy2019 <- ip_census_2019_df %>%
  group_by(CensusSite, UnitRollUp, UnitType, CENSUS_DEPT, CensusYear, CensusMonth) %>%
  summarize(Census = sum(Census)) %>%
  arrange(CensusSite, CensusYear, CensusMonth, UnitRollUp)


```

```{r Determine days per month for 2019 and 2020}

fy2019_days <- ip_census_2019_df %>%
  group_by(CensusSite, CensusYear, CensusMonth, CensusDate) %>%
  summarize(Days = 1)

fy2019_days_per_month <- fy2019_days %>%
  group_by(CensusSite, CensusYear, CensusMonth) %>%
  summarize(DaysPerMonth = n())

fy2020_days <- ip_census_crosswalk %>%
  filter(IPUnit & !is.na(CensusSite)) %>%
  group_by(CensusSite, CensusYear, CensusMonth, CensusDate) %>%
  summarize(Days = 1)

fy2020_days_per_month <- fy2020_days %>%
  group_by(CensusSite, CensusYear, CensusMonth) %>%
  summarize(DaysPerMonth = n())

days_per_month <- rbind(fy2019_days_per_month, fy2020_days_per_month)

```


```{r Summarize FY2020 data based on site and unit type}

# Summarize daily census for each unit organized grouped by site and unit type/roll up
census_site_unit_type <- ip_census_crosswalk %>%
  filter(IPUnit & CensusSite != "MSBI" & !is.na(CensusSite)) %>%
  group_by(CensusSite, UnitRollUp, UnitType, CENSUS_DEPT, CensusDate, CensusYear, CensusMonth) %>%
  summarize(Census = sum(PATIENT_DAY)) %>%
  arrange(CensusSite, CensusDate, UnitRollUp, CensusDate)

# Summarize daily adult census (ICU, Med Surg, COVID Surge) for each site
site_adult_census <- census_site_unit_type %>%
  filter(UnitType == "Adult ICU" | UnitType == "Adult MS" | UnitType == "COVID Surge") %>%
  group_by(CensusSite, CensusDate, CensusYear, CensusMonth) %>%
  summarize(Census = sum(Census))

# Summarize total monthly census for each unit organized by site and unit type/roll up; this will be used to compare 2019 to 2020 ADC
monthly_census_fy2020 <- ip_census_crosswalk %>%
  filter(IPUnit & CensusSite != "MSBI" & !is.na(CensusSite)) %>%
  group_by(CensusSite, UnitRollUp, UnitType, CENSUS_DEPT, CensusYear, CensusMonth) %>%
  summarize(Census = sum(PATIENT_DAY)) %>%
  arrange(CensusSite, CensusYear, CensusMonth, UnitRollUp)

```


```{r Combine monthly census for FY2019 and 2020 YTD}
monthly_census <- rbind(monthly_census_fy2019, monthly_census_fy2020)

# Crosswalk with days per month
monthly_census <- left_join(monthly_census, days_per_month, by = c("CensusSite" = "CensusSite", 
                                                                   "CensusYear" = "CensusYear",
                                                                   "CensusMonth" = "CensusMonth"))

monthly_census <- monthly_census %>%
  mutate(ADC = Census / DaysPerMonth,
         ValidMonth = ifelse(CensusSite == "MSB" & CensusYear == 2019 & CensusMonth <= 8, 0, 1),
         ModADC = ifelse(ValidMonth == 1, ADC, NA),
         ModDate = (as.Date(paste0(CensusMonth, "/1/", CensusYear), "%m/%d/%Y")))

```


```{r Create table for showing ADC deltas}
current_month <- month(max(ip_census_crosswalk$CensusDate))

include_months <- seq(current_month - (months_to_compare - 1), current_month, by = 1)

# Filter data to only include months of interest
census_monthly_comp <- monthly_census %>%
  filter(CensusMonth %in% include_months)

# Cast data to view 2019 and 2020 next to each other
census_monthly_comp_cast <- dcast(census_monthly_comp,
                                  CensusSite + UnitRollUp + CENSUS_DEPT ~ ModDate,
                                  value.var = "ModADC")

# Rename CENSUS_DEPT column
colnames(census_monthly_comp_cast)[3] <- "Unit"

# Reformat column names with dates
colnames(census_monthly_comp_cast)[4:ncol(census_monthly_comp_cast)] <- format(as.Date(colnames(census_monthly_comp_cast)[4:ncol(census_monthly_comp_cast)],
                                                                                       "%Y-%m-%d"), "%b-%y")
# Determine percent difference in census for each unit and each month
data_type <- lapply(census_monthly_comp_cast, class)

start_adc_col <- min(which(data_type == "numeric"))

census_monthly_comp_cast <- cbind(census_monthly_comp_cast, 
                                  lapply(start_adc_col:(ncol(census_monthly_comp_cast) - months_to_compare), 
                                         function(x) 
                                           setNames(((census_monthly_comp_cast[x + months_to_compare] -
                                                        census_monthly_comp_cast[x]) / census_monthly_comp_cast[x] * 100), 
                                                    substr(colnames(census_monthly_comp_cast)[x],
                                                                  start = 1, stop = 3))))

```


```{r Custom function for plotting site total adult census, results = 'asis'}

# Custom function for plotting total adult census for a given site
site_census_summary_plot <- function(site) {
  site_adult_census_plot_df <- site_adult_census %>%
    filter(CensusSite == site & CensusDate > start_date)
  
  ggplot(data = site_adult_census_plot_df, 
       aes(x = CensusDate, y = Census)) +
    geom_line(color = sinai_colors[1], group = 1) +
    geom_point(color = sinai_colors[1]) +
    labs(title = paste(site, "Total Adult Census (ICU, Med Surg, COVID Surge)"), x = "Date", y = "Census") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, hjust = 0.5),
          legend.position = "bottom",
          legend.box = "horizontal",
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 10),
          axis.text.x = element_text(size = 10, angle = 45, vjust = 0.5),
          axis.text.y = element_text(size = 10),
          panel.grid.major = element_line(color = "lightgrey"),
          panel.grid.minor = element_line(color = "lightgrey")) +
    scale_x_date(date_breaks = "7 days", minor_breaks = "1 day", date_labels = "%m/%d/%y",
                 expand = c(0, 1))
  
}

```


```{r Custom function for plotting unit level census data for a given site, results = 'asis'}

# Custom function for plotting unit level census census
unit_type_census_plot <- function(data, title) {
  
  num_units <- length(unique(data$CENSUS_DEPT))
  
  census_trend_plot <- ggplot(data = data,
                              aes(x = CensusDate, y = Census, color = CENSUS_DEPT)) +
    geom_line() +
    geom_point() +
    labs(title = title, x = "Date", y = "Census") +
    theme_bw() +
    theme(plot.title = element_text(size = 14, hjust = 0.5),
          legend.position = "bottom",
          legend.box = "horizontal",
          legend.title = element_text(size = 10),
          legend.text = element_text(size = 10),
          axis.text.x = element_text(size = 10, angle = 45, vjust = 0.5),
          axis.text.y = element_text(size = 10),
          panel.grid.major = element_line(color = "lightgrey"),
          panel.grid.minor = element_line(color = "lightgrey")) +
    scale_color_manual(name = "Unit", values = sinai_colors[1:length(unique(data$CENSUS_DEPT))]) +
    scale_x_date(date_breaks = "7 days", minor_breaks = "1 day", date_labels = "%m/%d/%y",
                 expand = c(0, 1), limits = c(start_date + 1, Sys.Date() - 1))
  
  print(census_trend_plot)

}

```


```{r Custom function for creating tables with ADC delta for each unit type, results = 'asis'}

# Custom function for 2019 and 2020 monthly census comparison
census_compare_kable <- function(data, table_caption) {
  
  site_unit_census_kable <-  kable(data[ , 3:ncol(data)], format = "html", escape = FALSE, align = "c", digits = 1,
      caption = table_caption) %>%
    kable_styling(bootstrap_options = "hover", position = "center", font_size = 11, full_width = FALSE) %>%
    column_spec(column = c(1, 4, 7), border_right = "thin solid lightgray") %>%
    column_spec(column = c(2:4), background = sinai_colors[1], color = "white", include_thead =  TRUE) %>%
    column_spec(column = c(5:7), background = sinai_colors[2], color = "white", include_thead =  TRUE) %>%
    column_spec(column = c(8:10), background = sinai_colors[4], color = "white", include_thead = TRUE) %>%
    column_spec(column = c(2:10), background = "inherit", color = "inherit") %>%  
    add_header_above(c(" " = 1, "2019 Monthly ADC" = 3, "2020 Monthly ADC" = 3, "Percent Difference" = 3), 
                     background = c("", sinai_colors[1], sinai_colors[2], sinai_colors[4]), color = "white", line = FALSE)
  
  print(site_unit_census_kable)

}

```


```{r Custom function for iterating through data for a given site, results = 'asis'}
# Custom function to iterate through a site's unit types

site_census_visual_agg <- function(site) {
  
  cat("<h3>Total Census</h3>")
  plot(site_census_summary_plot(site = site))

  # Subset census data based on site and start date
  site_df <- census_site_unit_type %>%
    filter(CensusSite == site & CensusDate > start_date)
  
  # Subset census data based on site and start date
  site_census_comp_kable <- census_monthly_comp_cast %>%
    filter(CensusSite == site)
  
  # Determine unit types for this site
  unit_types <- unique(site_df$UnitRollUp)
  
  for(i in unit_types){
    
    cat("<h3>", i, "</h3>")
    
    # Subset data to plot based on unit type roll up at this site
    plot_df <- site_df %>%
      filter(UnitRollUp == i)
    
    # Determine if the number of units within this unit type exceeds the 
    # maximum number of units to plot on a given graph
    num_units <- length(unique(plot_df$CENSUS_DEPT))

    
    if(num_units <= max_num_units) {

      # If the number of units does not exceed the maximum number of units per graph,
      # specify the title and plot the data as is
      plot_title <- paste0(site, " ", i, " Census by Unit")

      unit_type_census_plot(data = plot_df, title = plot_title)

    } else {

      # If the number of units exceeds the maximum number of units per graph, establish groupings
      # based on the total number of units and the maximum number of units per graph
      unit_numbers <- data.frame("Unit" = unique(plot_df$CENSUS_DEPT), stringsAsFactors = FALSE)
      unit_numbers <- unit_numbers %>%
        mutate(Number = row_number(),
               Grouping = ceiling(Number / max_num_units))

      # Add text to plot title to include number of graphs for this unit type
      plot_df <- left_join(plot_df, unit_numbers[ , c("Unit", "Grouping")], by = c("CENSUS_DEPT" = "Unit"))

      for(j in 1:max(plot_df$Grouping)) {
        grouping_df <- plot_df %>%
          filter(Grouping == j)

        plot_title <- paste0(site, " ", i, " Census by Unit (", j, " of ", max(plot_df$Grouping), ")")

        unit_type_census_plot(data = grouping_df, plot_title)
      }

    }

    unit_type_census_comp_kable <- site_census_comp_kable %>%
      filter(UnitRollUp == i)
    
    kable_title <- paste(site, i, " ADC: 2019 vs. 2020 for Last 3 Months")
    
    census_compare_kable(data = unit_type_census_comp_kable, table_caption = kable_title)
    
  }
  
}


```


## MSH
```{r Plot MSH census trends, results = 'asis'}
site_census_visual_agg(site = "MSH")

```


## MSQ
```{r Plot MSQ census trends, results = 'asis'}
site_census_visual_agg(site = "MSQ")

```


## MSB
*MSB IP Epic go-live occurred on 09/08/2019. ADC reflects this start date and year-to-year comparisons prior to September 2019 are not available.*
```{r Plot MSB census trends, results = 'asis'}
site_census_visual_agg(site = "MSB")

```


## MSM
```{r Plot MSM census trends, results = 'asis'}
site_census_visual_agg(site = "MSM")

```


## MSW
```{r Plot MSW census trends, results = 'asis'}
site_census_visual_agg(site = "MSW")

```


```{r Test multiple graphs using lapply}

# site <- "MSH"
# 
# # Custom function for plotting unit level census census
# unit_type_census_plot2 <- function(data, title) {
#   
#   num_units <- length(unique(data$CENSUS_DEPT))
#   
#   ggplot(data = data, aes(x = CensusDate, y = Census, color = CENSUS_DEPT)) +
#     geom_line() +
#     geom_point() +
#     labs(title = title, x = "Date", y = "Census") +
#     theme_bw() +
#     theme(plot.title = element_text(size = 14, hjust = 0.5),
#           legend.position = "bottom",
#           legend.box = "horizontal",
#           legend.title = element_text(size = 10),
#           legend.text = element_text(size = 10),
#           axis.text.x = element_text(size = 10, angle = 45, vjust = 0.5),
#           axis.text.y = element_text(size = 10),
#           panel.grid.major = element_line(color = "lightgrey"),
#           panel.grid.minor = element_line(color = "lightgrey")) +
#     scale_color_manual(name = "Unit", values = sinai_colors[1:length(unique(data$CENSUS_DEPT))]) +
#     scale_x_date(date_breaks = "7 days", minor_breaks = "1 day", date_labels = "%m/%d/%y",
#                  expand = c(0, 1), limits = c(start_date + 1, Sys.Date() - 1))
#   
#   # print(census_trend_plot)
# 
# }
# 
# 
# 
# # Subset census data based on site and start date
# site_df <- census_site_unit_type %>%
#     filter(CensusSite == site & CensusDate > start_date)
# 
# # Determine unit types for this site
# unit_types <- unique(site_df$UnitRollUp)
# 
# lapply(unit_types, function(x) {
#   plot_df <- site_df %>%
#     filter(UnitRollUp == x)
#   
#   num_units <- length(unique(plot_df$CENSUS_DEPT))
#   
#   if (num_units <= max_num_units) {
#     
#     plot_title <- paste(site, x, "Census by Unit")
#     
#     unit_type_census_plot2(data = plot_df, title = plot_title)
#     
#   } else {
#     
#       # If the number of units exceeds the maximum number of units per graph, establish groupings
#       # based on the total number of units and the maximum number of units per graph
#       unit_numbers <- data.frame("Unit" = unique(plot_df$CENSUS_DEPT), stringsAsFactors = FALSE)
#       unit_numbers <- unit_numbers %>%
#         mutate(Number = row_number(),
#                Grouping = ceiling(Number / max_num_units))
# 
#       # Add text to plot title to include number of graphs for this unit type
#       plot_df <- left_join(plot_df, unit_numbers[ , c("Unit", "Grouping")], by = c("CENSUS_DEPT" = "Unit"))
#       
#       groupings <- seq(1, max(plot_df$Grouping), 1)
#       
#       lapply(groupings, function(y) {
#         
#         grouping_df <- plot_df %>%
#           filter(Grouping == y)
#         
#         plot_title <- paste(site, x, "Census by Unit (", y, "of", max(groupings), ")")
#         
#         unit_type_census_plot2(data = grouping_df, title = plot_title)
#       
#       
#       })
# 
#   }
#     
# })




```