---
title: "FY2019 MSHS ADC"
date: "07/15/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r Install and load packages}
# Code for analyzing historical COVID-19 IP census, admissions, and discharges ----------------------

#Install and load necessary packages --------------------
#install.packages("readraw_dfl")
#install.packages("writeraw_dfl")
#install.packages("ggplot2")
#install.packages("lubridate")
#install.packages("dplyr")
#install.packages("reshape2")
#install.packages("svDialogs")
#install.packages("stringr")
#install.packages("formattable")
# install.packages("ggpubr")
# install.packages("rprojroot")

# Load libraries ------------------------
library(readxl)
library(writexl)
library(ggplot2)
library(lubridate)
library(dplyr)
library(reshape2)
library(svDialogs)
library(stringr)
library(formattable)
library(scales)
library(reshape2)
library(knitr)
library(rmarkdown)
library(kableExtra)

```

```{r Determine drive mapping}
rm(list = ls())

if (list.files("J://") == "Presidents") {
  user_directory <- "J:/Presidents/HSPI-PM/Operations Analytics and Optimization/Projects/System Operations/COVID Scenario Testing"
} else {
  user_directory <- "J:/deans/Presidents/HSPI-PM/Operations Analytics and Optimization/Projects/System Operations/COVID Scenario Testing"
}

```


```{r Import raw data}
# Set working directory and select raw data ----------------------------

covid_trend_start_date <- as.Date("3/12/20", format = "%m/%d/%y")

covid_steady_state_start <- as.Date("6/8/20", format = "%m/%d/%y")

sinai_colors <- c("#221f72", "#00AEEF", "#D80B8C", "#4C4D4C", "#8988dd", "#B2B3B2", "#F887CE")

site_order <- c("MSH", "MSQ", "MSB", "MSBI", "MSM", "MSW", "MSHS")

flu_season_order <- c("Non-Flu", "Flu")

# Import FY2019 IP discharge data
ip_disch_df_raw <- read_excel(paste0(user_directory, "/IP Discharge Data/IP Disch FY2019 2020-05-13.xlsx"), na = c("", "NA"),
                                col_types = c("text", "text", "text", "text", "date", "date", "date",
                                              "text", "text", "text", "text", "text", "text", "text",
                                              "numeric", "numeric"))

# 
# Import analysis reference
reference_file <- paste0(user_directory, "/IP Discharge Data/Analysis Reference 2020-06-11.xlsx")
ref_sheets <- excel_sheets(reference_file)

ref_data <- lapply(ref_sheets, function(x) read_excel(reference_file, sheet = x))

site_ref <- ref_data[[1]]
dispo_ref <- ref_data[[2]]
service_line_ref <- ref_data[[3]]
ip_disch_units_ref <- ref_data[[4]]

rb_charge_ipd_ref <- ref_data[[5]]
rb_charge_site_ref <- ref_data[[6]]
rb_charge_accom_ref <- ref_data[[7]]

```

```{r Format IP discharge data}
# Format inpatient days dataframe ----------------------------------
ip_disch_df <- ip_disch_df_raw

# Create columns with census, admit, and discharge dates
ip_disch_df <- ip_disch_df %>%
  mutate(AdmitDate = date(`Admit Dt Src`),
         DischDate = date(`Dsch Dt Src`),
         AdmitMonth = month(AdmitDate),
         DischMonth = month(DischDate))

# Determine admit source
ip_disch_df <- ip_disch_df %>%
  mutate(AdmitType = ifelse(is.na(`Admit Type Desc Msx`) | str_detect(`Admit Type Desc Msx`, "(INFORMATION NOT AVAILABLE)"), "NonElective",
                            ifelse(str_detect(`Admit Type Desc Msx`, "ELECTIVE"), "Elective",
                            ifelse(str_detect(`Admit Type Desc Msx`, "NEWBORN"), "Newborn",
                                   ifelse(str_detect(`Admit Type Desc Msx`, "(EMERGENCY)|(URGENT)"), "NonElective", "Other")))))

# Crosswalk raw data with reference data -------------------------
# Crosswalk sites
ip_disch_df <- left_join(ip_disch_df, site_ref, by = c("Facility Msx" = "Facility Msx"))

# Crosswalk service lines to include/exclude
ip_disch_df <- left_join(ip_disch_df, service_line_ref[ , c("Service Desc Msx", "ServiceInclude")], by = c("Service Desc Msx" = "Service Desc Msx"))

# If no discharge unit present, set to "Unknown"
ip_disch_df[is.na(ip_disch_df$`Unit Desc Msx`), "Unit Desc Msx"] <- "Unknown"

# Crosswalk unit to determine if it is an ICU, peds unit, nursery/NICU,
ip_disch_df <- left_join(ip_disch_df, ip_disch_units_ref, by = c("Site" = "Site", "Unit Desc Msx" = "Unit Desc Msx"))


```

```{r Susbet data frame based on unit and patient type and then summarize}
# # Inclusion criteria
# # Remove any peds encounters
# # Remove NICU and newborn discharges
# # Include any encounter with an ICU LOS > 0 OR any patient discharged from an adult med/surg unit
# ip_disch_subset <- ip_disch_df %>%

#   filter(PedsUnit == "No" & NurseryNICU == "No" & AdmitType != "Newborn" & (`Icu Days Msx` > 0 | AdultMedSurg == "Yes"))

# Exclusion criteria
# Remove any chem dependency, psych, rehab, peds, newborn, neonatal, and OB encounters
# Remove any encounter with "Newborn" as admit type
ip_disch_subset <- ip_disch_df %>%
  filter(ServiceInclude == "Yes" & AdmitType != "Newborn")


ip_disch_days_site <- ip_disch_subset %>%
  group_by(Site) %>%
  summarize(TotalDisch = n(),
            TotalDays = sum(`Los No Src`),
            ICUDays = sum(`Icu Days Msx`),
            NonICUDays = TotalDays - ICUDays) %>%
  ungroup()

ip_disch_days_mshs <- ip_disch_subset %>%
  summarize(Site = "MSHS",
            TotalDisch = n(),
            TotalDays = sum(`Los No Src`),
            ICUDays = sum(`Icu Days Msx`),
            NonICUDays = TotalDays - ICUDays) %>%
  ungroup()

# Bind data for sites and system together
ip_disch_days_summary <- rbind(ip_disch_days_site, ip_disch_days_mshs)

# Calculate ADC based on patient days
ip_disch_days_summary <- ip_disch_days_summary %>%
  mutate(TotalADC = TotalDays / 365,
         ICUADC = ICUDays / 365,
         NonICUADC = NonICUDays / 365)

ip_disch_days_summary$Site <- factor(ip_disch_days_summary$Site, levels = site_order, 
                                     ordered = TRUE)

ip_disch_days_summary <- ip_disch_days_summary %>%
  arrange(Site)

# Create a table summarizing patient days and ADC
kable(ip_disch_days_summary, format = "html", escape = FALSE, align = "c", digits = 1,
      col.names =c("Site", "Discharges", "Total", "ICU", "Med Surg",
                   "Total", "ICU", "Med Surg"),
      caption = "FY2019 ADC by Site") %>%
  kable_styling(bootstrap_options = "hover", position = "center", font_size = 11, full_width = FALSE) %>%
  column_spec(column = c(1, 2, 5), border_right = "thin solid lightgray") %>%
  # column_spec(column = c(2), background = sinai_colors[4], color = "white", include_thead =  TRUE) %>%
  column_spec(column = c(3:5), background = sinai_colors[1], color = "white", include_thead =  TRUE) %>%
  column_spec(column = c(6:8), background = sinai_colors[2], color = "white", include_thead =  TRUE) %>%
  column_spec(column = c(2:8), background = "inherit", color = "inherit") %>%  
  # row_spec(row = 0, background = "#221f72", color = "white") %>%
  row_spec(row = nrow(ip_disch_days_summary), background = "lightgrey", bold = T) %>%
  add_header_above(c(" " = 1, " " = 1, "Patient Days" = 3, "ADC" = 3), background = c("", sinai_colors[4], sinai_colors[1], sinai_colors[2]), color = "white", line = FALSE)


```

**Data Source:**</br>
FY2019 ICU ADC based on billing data for patients discharged from 1/1/2019-12/31/2019.</br>
Analysis excludes peds, nursery/neonatal, obstetrics, psych, rehab, and chemical dependency encounters.
<h4></h4></br>






