---
title: "Census-Trending-Dashboard"
author: "HSO"
output: html_document
---


```{r Install and load packages}
# install.packages("DBI")
# install.packages("odbc")
# install.packages("dplyr")
# install.packages("dbplyr")
# install.packages("lubridate")
# install.packages("readxl")
# install.packages("writexl")
# install.packages("ggplot2")
# install.packages("lubridate")
# install.packages("reshape2")
# install.packages("svDialogs")
# install.packages("stringr")
# install.packages("formattable")
# install.packages("scales")
# install.packages("knitr")
# install.packages("rmarkdown")
# install.packages("kableExtra")

library(DBI)
library(odbc)
library(dplyr)
library(dbplyr)
library(lubridate)
library(readxl)
library(writexl)
library(ggplot2)
library(lubridate)
library(reshape2)
library(svDialogs)
library(stringr)
library(formattable)
library(scales)
library(knitr)
library(rmarkdown)
library(kableExtra)

```


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, fig.align = "center")
```


```{r Determine drive mapping}
rm(list = ls())

if (list.files("J://") == "Presidents") {
  user_directory <- "J:/Presidents/HSPI-PM/Operations Analytics and Optimization/Projects/System Operations/COVID Scenario Testing"
} else {
  user_directory <- "J:/deans/Presidents/HSPI-PM/Operations Analytics and Optimization/Projects/System Operations/COVID Scenario Testing"
}

```

```{r Establish connection to Oracle database and import IP census and COVID data}
# Establish connection to Oracle database
con <- dbConnect(odbc(), 
                 Driver = "Oracle in OraClient12Home1", 
                 DBQ = "idf02-scan/IDMREPD",
                 Schema = "COO_USER",
                 UID = "COO_USER",
                 PWD = "CO02O02rPaVc*MqP", 
                 Port = 1521)


# Import IP census for Epic sites
start1 <- proc.time()

oracle_ip_census_df <- tbl(con, "EMR_ALL_PAT_DAYS_MSX") %>%
  filter(year(CENSUS_DATE) == 2020) %>%
  collect()

end1 <- proc.time() - start1         

# Import COVID census for Epic sites
start2 <- proc.time()

oracle_covid_census_df <- tbl(con, "COVID_IP_PATIENT_DAYS_DETAIL") %>%
  filter(year(CENSUS_DATE) == 2020 & 
           !(IP_SITE %in% c("MSSN", "MSBI", "UNDETERMINED"))) %>%
  collect()

end2 <- proc.time() - start2

```


```{r Import unit mappings reference file}
unit_mapping <- read_excel(path = paste0(user_directory, "/Epic Census Trending/Epic-Oracle-Census-Unit-Mappings-2020-07-29.xlsx"),
                           sheet = "UnitMappings",
                           na = c("", "NA"))


```


```{r Subset, format, and crosswalk Oracle data}

# Remove duplicates and select relevant columns from COVID data
covid_census_subset <- unique(oracle_covid_census_df)

covid_census_subset <- covid_census_subset %>%
  select(CSN, MRN, EXTERNAL_ENC_ID, CENSUS_DATE, 
         CENSUS_DEPT, CENSUS_ROOM, CENSUS_BED,
         ACCOMMODATION_DESC,
         PAT_DAY_INF_STATUS) %>%
  arrange(CSN, CENSUS_DATE, CENSUS_DEPT)

# Remove duplicates from IP census data
ip_census_subset <- unique(oracle_ip_census_df)

ip_census_subset <- ip_census_subset %>%
  arrange(CSN, CENSUS_DATE, CENSUS_DEPT)


# Crosswalk IP census with COVID data to determine daily COVID volume
ip_census_crosswalk <- left_join(ip_census_subset, covid_census_subset,
                          by = c("CSN" = "CSN", 
                                 "MRN" = "MRN",
                                 "EXTERNAL_ENC_ID" = "EXTERNAL_ENC_ID",
                                 "CENSUS_DATE" = "CENSUS_DATE", 
                                 "CENSUS_DEPT" = "CENSUS_DEPT",
                                 "CENSUS_ROOM" = "CENSUS_ROOM",
                                 "ACCOMMODATION_DESC" = "ACCOMMODATION_DESC",
                                 "CENSUS_BED" = "CENSUS_BED"))

# Format crosswalked data
ip_census_crosswalk <- ip_census_crosswalk %>%
  mutate(CensusDate = as.Date(CENSUS_DATE),
         CensusYear = year(CensusDate),
         CensusMonth = month(CensusDate),
         AdjPatInfStat = ifelse(PAT_DAY_INF_STATUS %in% c("COVID-19", "PUI - COVID", "SUSC COVID"),
                                PAT_DAY_INF_STATUS, NA))

# Crosswalk census data with unit mappings
ip_census_crosswalk <- left_join(ip_census_crosswalk, unit_mapping,
                                 by = c("CENSUS_DEPT" = "CENSUS_DEPT"))

# Order unit types for plotting
unit_type_order <- c("ICU", "Med Surg", "COVID Surge", "Peds & Peds ICU", "L&D & Postpartum",
                     "Nursery & NICU", "Psych & Rehab", "ED", "Psych ED", "Non-IP")

ip_census_crosswalk$UnitRollUp <- factor(ip_census_crosswalk$UnitRollUp, 
                                         levels = unit_type_order, ordered = TRUE)


```


```{r Begin summarizing data based on site and unit type}
census_site_unit_type <- ip_census_crosswalk %>%
  filter(IPUnit & CensusSite != "MSBI") %>%
  group_by(CensusSite, UnitRollUp, UnitType, CENSUS_DEPT, CensusDate, CensusYear, CensusMonth) %>%
  summarize(Census = sum(PATIENT_DAY)) %>%
  arrange(CensusSite, CensusDate, UnitRollUp, CensusDate)

```


```{r Plot census trend}

sinai_colors <- c("#221f72", "#00AEEF", "#D80B8C", "#4C4D4C", "#8988dd", "#B2B3B2", "#F887CE", "#79DCFF", "#8F075B", "#00668A")

# Assume 4 week lookback period for now
lookback_period <- 28

# Determine start date for trending data based on lookback period
start_date <- (Sys.Date() - 1) - (lookback_period)

# test_df <- census_site_unit_type %>%
  # filter(CensusSite == "MSW",
  #        CensusDate > start_date,
  #        UnitRollUp == "ICU")

test_df <- census_site_unit_type %>%
  filter(CensusSite == "MSH",
         CensusDate > start_date,
         UnitRollUp == "Med Surg")

# unit_number <- data.frame("Unit" = as.character(unique(test_df$CENSUS_DEPT)))
# 
# unit_number <- unit_number %>%
#   mutate(Number = row_number(),
#          Grouping = ceiling(Number / 6))
# 
# test_df <- left_join(test_df, unit_number[ , c("Unit", "Grouping")],
#                      by = c("CENSUS_DEPT" = "Unit"))


if (length(unique(test_df$CENSUS_DEPT)) > 6) {
  unit_number <- data.frame("Unit" = as.character(unique(test_df$CENSUS_DEPT)))
  
  unit_number <- unit_number %>%
    mutate(Number = row_number(), 
           Grouping = ceiling(Number / 6))
    
  test_df <- left_join(test_df, unit_number[ , c("Unit", "Grouping")],
                       by = c("CENSUS_DEPT" = "Unit"))
  
  for (j in 1:max(test_df$Grouping)) {
    plot_data <- test_df %>%
      filter(Grouping == j)
    
    test_plot <- ggplot(data = plot_data, aes(x = CensusDate, y = Census, color = CENSUS_DEPT, shape = CENSUS_DEPT)) +
      geom_line() +
      geom_point() +
      labs(title = paste0("Census Test ", j, " of ", max(test_df$Grouping)), x = "Date", y = "Census") +
      theme_bw() +
      theme(plot.title = element_text(size = 14, hjust = 0.5),
            legend.position = "bottom",
            legend.box = "horizontal",
            legend.title = element_text(size = 10),
            legend.text = element_text(size = 10),
            axis.text.x = element_text(size = 10, angle = 45, vjust = 0.5),
            axis.text.y = element_text(size = 10),
            panel.grid.major = element_line(color = "lightgrey"),
            panel.grid.minor = element_line(color = "lightgrey")) +
      scale_color_manual(name = "Unit", values = sinai_colors[1:6]) +
      scale_shape(name = "Unit") +
      scale_x_date(date_breaks = "7 days", minor_breaks = "1 day", date_labels = "%m/%d/%y",
               expand = c(0, 1))
    
    print(test_plot)
  }
}





ggplot(data = test_df, aes(x = CensusDate, y = Census, color = CENSUS_DEPT, shape = CENSUS_DEPT)) +
  geom_line() +
  geom_point() +
  labs(title = "MSW ICU Census by Unit", x = "Date", y = "Census") +
  theme_bw() +
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "bottom",
        legend.box = "horizontal",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, angle = 45, vjust = 0.5),
        axis.text.y = element_text(size = 10),
        panel.grid.major = element_line(color = "lightgrey"),
        panel.grid.minor = element_line(color = "lightgrey")) +
  scale_color_manual(name = "Unit", values = sinai_colors[1:3]) +
  scale_shape(name = "Unit") +
  scale_x_date(date_breaks = "7 days", minor_breaks = "1 day", date_labels = "%m/%d/%y",
               expand = c(0, 1))
  

```


```{r Custom function for looping through a given site}

msw_df <- census_site_unit_type %>%
  filter(CensusSite == "MSW",
         CensusDate > start_date)


unit_groupings <- unique(msw_df$UnitRollUp)

for(i in 1:length(unit_groupings)){
  unit_type <- unit_groupings[i]
  
  msw_df_subset <- msw_df %>%
    filter(UnitRollUp == unit_type)
  
  unit_type_plot <- ggplot(data = msw_df_subset, 
                           aes(x = CensusDate, y = Census, color = CENSUS_DEPT, shape = CENSUS_DEPT)) +
  geom_line() +
  geom_point() +
  labs(title = paste0("MSW ", unit_type, " Census by Unit"), x = "Date", y = "Census") +
  theme_bw() +
  theme(plot.title = element_text(size = 14, hjust = 0.5),
        legend.position = "bottom",
        legend.box = "horizontal",
        legend.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        axis.text.x = element_text(size = 10, angle = 45, vjust = 0.5),
        axis.text.y = element_text(size = 10),
        panel.grid.major = element_line(color = "lightgrey"),
        panel.grid.minor = element_line(color = "lightgrey")) +
  scale_color_manual(name = "Unit", values = sinai_colors[1:length(unique(msw_df_subset$CENSUS_DEPT))]) +
  scale_shape(name = "Unit") +
  scale_x_date(date_breaks = "7 days", minor_breaks = "1 day", date_labels = "%m/%d/%y",
               expand = c(0, 1))
  
  
  print(unit_type_plot)
}


```


```{r Custom function for looping through summarized data for each site, warning = TRUE, message = TRUE}

census_sites <- unique(census_site_unit_type$CensusSite)

# Iterate through each site
for(i in 1:length(census_sites)) {
  
  # Save the site
  site <- census_sites[i]
  
  # Subset summarized data for this site
  site_df <- census_site_unit_type %>%
    filter(CensusSite == site & CensusDate > start_date)
  
  # Determine unit types for this site
  unit_types <- unique(site_df$UnitRollUp) 
  
  # Iterate through unit types
  for(j in 1:length(unit_types)) {
    
    # Save the unit type
    unit_type <- unit_types[j]
    
    # Subset data for plotting by unit type
    unit_type_df <- site_df %>%
      filter(UnitRollUp == unit_type)
    
    unit_numbers <- data.frame("Unit" = (unique(unit_type_df$CENSUS_DEPT)),
                               stringsAsFactors = FALSE)
    
    unit_numbers <- unit_numbers %>%
      mutate(Number = row_number(),
             Grouping = ceiling(Number / 6))
    
    unit_type_df <- left_join(unit_type_df, unit_numbers[ , c("Unit", "Grouping")],
                              by = c("CENSUS_DEPT" = "Unit"))
    
    for(k in 1:max(unit_type_df$Grouping)) {
      plot_unit_type_df <- unit_type_df %>%
        filter(Grouping == k)
      
      site_unit_type_plot <- ggplot(data = plot_unit_type_df, 
                           aes(x = CensusDate, y = Census, color = CENSUS_DEPT, shape = CENSUS_DEPT)) +
      geom_line() +
      geom_point() +
      labs(title = ifelse(max(unit_type_df$Grouping) == 1, paste0(site, " ", unit_type, " Census by Unit"),
                          paste0(site, " ", unit_type, " Census by Unit (", k, " of ", max(unit_type_df$Grouping), ")")), x = "Date", y = "Census") +
      theme_bw() +
      theme(plot.title = element_text(size = 14, hjust = 0.5),
            legend.position = "bottom",
            legend.box = "horizontal",
            legend.title = element_text(size = 10),
            legend.text = element_text(size = 10),
            axis.text.x = element_text(size = 10, angle = 45, vjust = 0.5),
            axis.text.y = element_text(size = 10),
            panel.grid.major = element_line(color = "lightgrey"),
            panel.grid.minor = element_line(color = "lightgrey")) +
      scale_color_manual(name = "Unit", values = sinai_colors[1:length(unique(plot_unit_type_df$CENSUS_DEPT))]) +
      scale_shape(name = "Unit") +
      scale_x_date(date_breaks = "7 days", minor_breaks = "1 day", date_labels = "%m/%d/%y",
               expand = c(0, 1))
  
  
  print(site_unit_type_plot)
      
    }
    
  #   site_unit_type_plot <- ggplot(data = unit_type_df, 
  #                          aes(x = CensusDate, y = Census, color = CENSUS_DEPT)) + #, shape = CENSUS_DEPT)) +
  #     geom_line() +
  #     geom_point() +
  #     labs(title = paste0(site, " ", unit_type, " Census by Unit"), x = "Date", y = "Census") +
  #     theme_bw() +
  #     theme(plot.title = element_text(size = 14, hjust = 0.5),
  #           legend.position = "bottom",
  #           legend.box = "horizontal",
  #           legend.title = element_text(size = 10),
  #           legend.text = element_text(size = 10),
  #           axis.text.x = element_text(size = 10, angle = 45, vjust = 0.5),
  #           axis.text.y = element_text(size = 10),
  #           panel.grid.major = element_line(color = "lightgrey"),
  #           panel.grid.minor = element_line(color = "lightgrey")) +
  #     scale_color_manual(name = "Unit", values = sinai_colors[1:length(unique(unit_type_df$CENSUS_DEPT))]) +
  #     # scale_shape(name = "Unit") +
  #     scale_x_date(date_breaks = "7 days", minor_breaks = "1 day", date_labels = "%m/%d/%y",
  #              expand = c(0, 1))
  # 
  # 
  # print(site_unit_type_plot)
    
    
  }
  
}





```
